name: Laravel Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Pull main
        run: |
          git pull

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ROOT }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.ED25519 }}
          script: |
            cd /var/www/html
            
            echo "Application in maintenance mode"
            
            # maintenance mode
            php artisan down
            
            composer install --no-interaction --prefer-dist --optimize-autoloader
            
            php artisan migrate --force
            php artisan optimize
            chmod -R 777 storage bootstrap/cache
            
            # Reload PHP to update opcache
            echo "" | sudo -S service php8.1-fpm reload
            
            npm install
            npm run build
            
            # Exit maintenance mode
            php artisan up
            
            echo "Application deployed!"
