name: Laravel Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ROOT }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.ED25519 }}
          script: |
            cd /var/www/html
            chmod +x .github/scripts/DeployScript.sh
            .github/scripts/DeployScript.sh
